version: '2.1'

services:
  yoda-voice-intro:
    image: yoda-voice-intro
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3050:3050
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js